package com.woorinet.plugin.demo.DTO.TL1;


import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
@Data



public class PM_PORT {
    String TID;
    String AID;
    String UNIT;
    String TYPE;
    String DATE;
    String TIME;
    int IN_OCTETS;
    int IN_OK_PACKETS;
    int IN_UNICAST_PACKETS;
    int IN_NON_UNICAST_PACKETS;
    int IN_DISCARD_PACKETS;
    int IN_ERROR_PACKETS;
    int IN_BROADCAST_PACKETS;
    int IN_MULTICAST_PACKETS;
    int IN_PACKETS_64_OCTETS;
    int IN_PACKETS_65_TO_127_OCTETS;
    int IN_PACKETS_128_TO_255_OCTETS;
    int IN_PACKETS_256_TO_511_OCTETS;
    int IN_PACKETS_512_TO_1023_OCTETS;
    int IN_PACKETS_1024_TO_1518_OCTETS;
    int IN_PACKETS_1519_TO_MAX_OCTETS;
    int IN_PAUSE_PACKETS;
    int IN_ALIGNMENT_ERRORS;
    int IN_FCS_ERRORS;
    int IN_SYMBOL_ERRORS;
    int OUT_OCTETS;
    int OUT_OK_PACKETS;
    int OUT_UNICAST_PACKETS;
    int OUT_NON_UNICAST_PACKETS;
    int OUT_DISCARD_PACKETS;
    int OUT_ERROR_PACKETS;
    int OUT_BROADCAST_PACKETS;
    int OUT_MULTICAST_PACKETS;
    int OUT_PAUSE_PACKETS;
    int IN_RATE;
    int OUT_RATE;
    double IN_LOSS_RATIO;
    double OUT_LOSS_RATIO;

    public PM_PORT() {

    }

    public PM_PORT(String TID, String AID, String UNIT, String TYPE, String DATE, String TIME, int IN_OCTETS, int IN_OK_PACKETS, int IN_UNICAST_PACKETS, int IN_NON_UNICAST_PACKETS, int IN_DISCARD_PACKETS, int IN_ERROR_PACKETS, int IN_BROADCAST_PACKETS, int IN_MULTICAST_PACKETS, int IN_PACKETS_64_OCTETS, int IN_PACKETS_65_TO_127_OCTETS, int IN_PACKETS_128_TO_255_OCTETS, int IN_PACKETS_256_TO_511_OCTETS, int IN_PACKETS_512_TO_1023_OCTETS, int IN_PACKETS_1024_TO_1518_OCTETS, int IN_PACKETS_1519_TO_MAX_OCTETS, int IN_PAUSE_PACKETS, int IN_ALIGNMENT_ERRORS, int IN_FCS_ERRORS, int IN_SYMBOL_ERRORS, int OUT_OCTETS, int OUT_OK_PACKETS, int OUT_UNICAST_PACKETS, int OUT_NON_UNICAST_PACKETS, int OUT_DISCARD_PACKETS, int OUT_ERROR_PACKETS, int OUT_BROADCAST_PACKETS, int OUT_MULTICAST_PACKETS, int OUT_PAUSE_PACKETS, int IN_RATE, int OUT_RATE, double IN_LOSS_RATIO, double OUT_LOSS_RATIO) {
        this.TID = TID;
        this.AID = AID;
        this.UNIT = UNIT;
        this.TYPE = TYPE;
        this.DATE = DATE;
        this.TIME = TIME;
        this.IN_OCTETS = IN_OCTETS;
        this.IN_OK_PACKETS = IN_OK_PACKETS;
        this.IN_UNICAST_PACKETS = IN_UNICAST_PACKETS;
        this.IN_NON_UNICAST_PACKETS = IN_NON_UNICAST_PACKETS;
        this.IN_DISCARD_PACKETS = IN_DISCARD_PACKETS;
        this.IN_ERROR_PACKETS = IN_ERROR_PACKETS;
        this.IN_BROADCAST_PACKETS = IN_BROADCAST_PACKETS;
        this.IN_MULTICAST_PACKETS = IN_MULTICAST_PACKETS;
        this.IN_PACKETS_64_OCTETS = IN_PACKETS_64_OCTETS;
        this.IN_PACKETS_65_TO_127_OCTETS = IN_PACKETS_65_TO_127_OCTETS;
        this.IN_PACKETS_128_TO_255_OCTETS = IN_PACKETS_128_TO_255_OCTETS;
        this.IN_PACKETS_256_TO_511_OCTETS = IN_PACKETS_256_TO_511_OCTETS;
        this.IN_PACKETS_512_TO_1023_OCTETS = IN_PACKETS_512_TO_1023_OCTETS;
        this.IN_PACKETS_1024_TO_1518_OCTETS = IN_PACKETS_1024_TO_1518_OCTETS;
        this.IN_PACKETS_1519_TO_MAX_OCTETS = IN_PACKETS_1519_TO_MAX_OCTETS;
        this.IN_PAUSE_PACKETS = IN_PAUSE_PACKETS;
        this.IN_ALIGNMENT_ERRORS = IN_ALIGNMENT_ERRORS;
        this.IN_FCS_ERRORS = IN_FCS_ERRORS;
        this.IN_SYMBOL_ERRORS = IN_SYMBOL_ERRORS;
        this.OUT_OCTETS = OUT_OCTETS;
        this.OUT_OK_PACKETS = OUT_OK_PACKETS;
        this.OUT_UNICAST_PACKETS = OUT_UNICAST_PACKETS;
        this.OUT_NON_UNICAST_PACKETS = OUT_NON_UNICAST_PACKETS;
        this.OUT_DISCARD_PACKETS = OUT_DISCARD_PACKETS;
        this.OUT_ERROR_PACKETS = OUT_ERROR_PACKETS;
        this.OUT_BROADCAST_PACKETS = OUT_BROADCAST_PACKETS;
        this.OUT_MULTICAST_PACKETS = OUT_MULTICAST_PACKETS;
        this.OUT_PAUSE_PACKETS = OUT_PAUSE_PACKETS;
        this.IN_RATE = IN_RATE;
        this.OUT_RATE = OUT_RATE;
        this.IN_LOSS_RATIO = IN_LOSS_RATIO;
        this.OUT_LOSS_RATIO = OUT_LOSS_RATIO;
    }

    @Override
    public String toString() {
        return "PM_PORT{" +
                "TID='" + TID + '\'' +
                ", AID='" + AID + '\'' +
                ", UNIT='" + UNIT + '\'' +
                ", TYPE='" + TYPE + '\'' +
                ", DATE='" + DATE + '\'' +
                ", TIME='" + TIME + '\'' +
                ", IN_OCTETS=" + IN_OCTETS +
                ", IN_OK_PACKETS=" + IN_OK_PACKETS +
                ", IN_UNICAST_PACKETS=" + IN_UNICAST_PACKETS +
                ", IN_NON_UNICAST_PACKETS=" + IN_NON_UNICAST_PACKETS +
                ", IN_DISCARD_PACKETS=" + IN_DISCARD_PACKETS +
                ", IN_ERROR_PACKETS=" + IN_ERROR_PACKETS +
                ", IN_BROADCAST_PACKETS=" + IN_BROADCAST_PACKETS +
                ", IN_MULTICAST_PACKETS=" + IN_MULTICAST_PACKETS +
                ", IN_PACKETS_64_OCTETS=" + IN_PACKETS_64_OCTETS +
                ", IN_PACKETS_65_TO_127_OCTETS=" + IN_PACKETS_65_TO_127_OCTETS +
                ", IN_PACKETS_128_TO_255_OCTETS=" + IN_PACKETS_128_TO_255_OCTETS +
                ", IN_PACKETS_256_TO_511_OCTETS=" + IN_PACKETS_256_TO_511_OCTETS +
                ", IN_PACKETS_512_TO_1023_OCTETS=" + IN_PACKETS_512_TO_1023_OCTETS +
                ", IN_PACKETS_1024_TO_1518_OCTETS=" + IN_PACKETS_1024_TO_1518_OCTETS +
                ", IN_PACKETS_1519_TO_MAX_OCTETS=" + IN_PACKETS_1519_TO_MAX_OCTETS +
                ", IN_PAUSE_PACKETS=" + IN_PAUSE_PACKETS +
                ", IN_ALIGNMENT_ERRORS=" + IN_ALIGNMENT_ERRORS +
                ", IN_FCS_ERRORS=" + IN_FCS_ERRORS +
                ", IN_SYMBOL_ERRORS=" + IN_SYMBOL_ERRORS +
                ", OUT_OCTETS=" + OUT_OCTETS +
                ", OUT_OK_PACKETS=" + OUT_OK_PACKETS +
                ", OUT_UNICAST_PACKETS=" + OUT_UNICAST_PACKETS +
                ", OUT_NON_UNICAST_PACKETS=" + OUT_NON_UNICAST_PACKETS +
                ", OUT_DISCARD_PACKETS=" + OUT_DISCARD_PACKETS +
                ", OUT_ERROR_PACKETS=" + OUT_ERROR_PACKETS +
                ", OUT_BROADCAST_PACKETS=" + OUT_BROADCAST_PACKETS +
                ", OUT_MULTICAST_PACKETS=" + OUT_MULTICAST_PACKETS +
                ", OUT_PAUSE_PACKETS=" + OUT_PAUSE_PACKETS +
                ", IN_RATE=" + IN_RATE +
                ", OUT_RATE=" + OUT_RATE +
                ", IN_LOSS_RATIO=" + IN_LOSS_RATIO +
                ", OUT_LOSS_RATIO=" + OUT_LOSS_RATIO +
                '}';
    }
}
